import { Types } from 'mongoose';
import { SeedData } from './seed-data.interface';
import { COLLECTIONS } from '../constants';

// NOTE on shape: this seed loads via the raw Mongo driver (see seed-loader.ts)
// which bypasses Mongoose validation — so the field shape MUST match the
// Location model exactly. The Location schema requires nested
// `address: { street, city, state, country, postalCode }` and
// `contactInfo: { email, phone }`, plus required `businessUnitId` /
// `countryId` ObjectIds. Earlier versions of this file used a flat shape
// (top-level `address: string`, `city`, `phone`, `email`) that silently
// inserted as malformed docs because raw inserts skip validation, leaving
// the public /locations endpoint with rows that had no `address.city`.
// For dev environments without seeded BUs/Countries, prefer the dedicated
// scripts/seed-default-locations.ts which resolves real refs at runtime.

export const locationSeedData: SeedData = {
    collection: COLLECTIONS.LOCATIONS,
    environment: 'all',
    idempotent: true,
    uniqueField: 'code',
    data: [
        // Hong Kong Locations
        {
            _id: new Types.ObjectId(),
            name: 'Cyberport',
            code: 'CYBERPORT',
            address: {
                street: 'Shop 123, Cyberport 3, 100 Cyberport Road',
                city: 'Hong Kong',
                state: 'Hong Kong',
                country: 'Hong Kong',
                postalCode: '00000',
            },
            contactInfo: {
                email: 'cyberport@proactivsports.net',
                phone: '+85222345678',
            },
            capacity: 100,
            facilities: ['Gym', 'Locker Rooms', 'Parking', 'Reception', 'Party Room'],
            isActive: true,
            status: 'ACTIVE',
            businessUnitId: null,
            countryId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isDeleted: false,
        },
        {
            _id: new Types.ObjectId(),
            name: 'Wan Chai',
            code: 'WAN-CHAI',
            address: {
                street: '5/F, 168 Hennessy Road',
                city: 'Wan Chai',
                state: 'Hong Kong',
                country: 'Hong Kong',
                postalCode: '00000',
            },
            contactInfo: {
                email: 'wanchai@proactivsports.net',
                phone: '+85223456789',
            },
            capacity: 80,
            facilities: ['Gym', 'Locker Rooms', 'Parent Lounge', 'Multi-Purpose Room'],
            isActive: true,
            status: 'ACTIVE',
            businessUnitId: null,
            countryId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isDeleted: false,
        },
        // USA Locations
        {
            _id: new Types.ObjectId(),
            name: 'Manhattan Center',
            code: 'MC-01',
            address: '123 Sports Avenue, Manhattan, New York',
            city: 'New York',
            state: 'New York',
            country: 'United States',
            postalCode: '10001',
            phone: '+1 (212) 555-0123',
            email: 'manhattan@proactivsports.net',
            capacity: 150,
            facilities: ['Gym', 'Pool', 'Parking', 'Locker Rooms', 'Cafeteria', 'Training Rooms'],
            isActive: true,
            status: 'ACTIVE',
            businessUnitId: null,
            countryId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isDeleted: false,
        },
        {
            _id: new Types.ObjectId(),
            name: 'Brooklyn Center',
            code: 'BC-01',
            address: '456 Fitness Boulevard, Brooklyn, New York',
            city: 'Brooklyn',
            state: 'New York',
            country: 'United States',
            postalCode: '11201',
            phone: '+1 (718) 555-0456',
            email: 'brooklyn@proactivsports.net',
            capacity: 120,
            facilities: ['Gym', 'Parking', 'Locker Rooms', 'Training Area'],
            isActive: true,
            status: 'ACTIVE',
            businessUnitId: null,
            countryId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isDeleted: false,
        },
        // Canada Locations
        {
            _id: new Types.ObjectId(),
            name: 'Etobicoke Center',
            code: 'EC-01',
            address: '789 Sports Lane, Etobicoke, Ontario',
            city: 'Etobicoke',
            state: 'Ontario',
            country: 'Canada',
            postalCode: 'M8Z 5K1',
            phone: '+1 (416) 555-0789',
            email: 'etobicoke@proactivsports.net',
            capacity: 110,
            facilities: ['Gym', 'Pool', 'Parking', 'Locker Rooms'],
            isActive: true,
            status: 'ACTIVE',
            businessUnitId: null,
            countryId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isDeleted: false,
        },
        // India Locations
        {
            _id: new Types.ObjectId(),
            name: 'Hyderabad',
            code: 'HYD-01',
            address: '321 Fitness Plaza, Hyderabad, Telangana',
            city: 'Hyderabad',
            state: 'Telangana',
            country: 'India',
            postalCode: '500001',
            phone: '+91 (40) 6666-0001',
            email: 'hyderabad@proactivsports.net',
            capacity: 100,
            facilities: ['Gym', 'Parking', 'Locker Rooms', 'Training Area'],
            isActive: true,
            status: 'ACTIVE',
            businessUnitId: null,
            countryId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isDeleted: false,
        },
        {
            _id: new Types.ObjectId(),
            name: 'Dubai',
            code: 'DXB-01',
            address: '654 Sports Complex, Dubai, UAE',
            city: 'Dubai',
            state: 'Dubai',
            country: 'United Arab Emirates',
            postalCode: '',
            phone: '+971 (4) 555-0654',
            email: 'dubai@proactivsports.net',
            capacity: 1,
            facilities: ['Gym', 'Parking'],
            isActive: true,
            status: 'ACTIVE',
            businessUnitId: null,
            countryId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isDeleted: false,
        },
        {
            _id: new Types.ObjectId(),
            name: 'Mumbai',
            code: 'MUM-01',
            address: '987 Fitness Hub, Mumbai, Maharashtra',
            city: 'Mumbai',
            state: 'Maharashtra',
            country: 'India',
            postalCode: '400001',
            phone: '+91 (22) 6666-0987',
            email: 'mumbai@proactivsports.net',
            capacity: 10,
            facilities: ['Gym', 'Parking', 'Locker Rooms'],
            isActive: true,
            status: 'ACTIVE',
            businessUnitId: null,
            countryId: null,
            createdAt: new Date(),
            updatedAt: new Date(),
            isDeleted: false,
        },
    ],
};