import { Types } from 'mongoose';
import { SeedData } from './seed-data.interface';
import { COLLECTIONS } from '../constants';

export const userSeedData: SeedData = {
    collection: COLLECTIONS.USERS,
    environment: 'development',
    idempotent: true,
    uniqueField: 'email',
    data: [
        // Passwords are pre-hashed: bcrypt.hashSync('Admin@123456', 10) etc.
        // Runner uses User model directly so hashing happens via pre-save hook
    ],
};

export const demoUsers = [
    {
        _id: new Types.ObjectId('507f1f77bcf86cd799439051'),
        email: 'admin@proactiv.com',
        password: 'Admin@123456',
        firstName: 'Admin',
        lastName: 'User',
        fullName: 'Admin User',
        role: 'ADMIN',
        permissions: ['*'],
        status: 'ACTIVE',
        isEmailVerified: true,
    },
    {
        _id: new Types.ObjectId('507f1f77bcf86cd799439055'),
        email: 'regional@proactiv.com',
        password: 'Regional@123456',
        firstName: 'Regional',
        lastName: 'Admin',
        fullName: 'Regional Admin',
        role: 'REGIONAL_ADMIN',
        permissions: ['region:read', 'region:write', 'location:read', 'reports:read'],
        status: 'ACTIVE',
        isEmailVerified: true,
    },
    {
        _id: new Types.ObjectId('507f1f77bcf86cd799439056'),
        email: 'franchise@proactiv.com',
        password: 'Franchise@123456',
        firstName: 'Franchise',
        lastName: 'Owner',
        fullName: 'Franchise Owner',
        role: 'FRANCHISE_OWNER',
        permissions: ['franchise:read', 'franchise:write', 'location:read', 'revenue:read'],
        status: 'ACTIVE',
        isEmailVerified: true,
    },
    {
        _id: new Types.ObjectId('507f1f77bcf86cd799439052'),
        email: 'manager@proactiv.com',
        password: 'Manager@123456',
        firstName: 'Location',
        lastName: 'Manager',
        fullName: 'Location Manager',
        role: 'LOCATION_MANAGER',
        permissions: ['location:read', 'location:write', 'staff:read', 'booking:read'],
        status: 'ACTIVE',
        isEmailVerified: true,
    },
    {
        _id: new Types.ObjectId('507f1f77bcf86cd799439053'),
        email: 'coach@proactiv.com',
        password: 'Coach@123456',
        firstName: 'Sarah',
        lastName: 'Coach',
        fullName: 'Sarah Coach',
        role: 'COACH',
        permissions: ['session:read', 'session:write', 'attendance:read', 'attendance:write'],
        status: 'ACTIVE',
        isEmailVerified: true,
    },
    {
        _id: new Types.ObjectId('507f1f77bcf86cd799439058'),
        email: 'partner@proactiv.com',
        password: 'Partner@123456',
        firstName: 'Partner',
        lastName: 'Admin',
        fullName: 'Partner Admin',
        role: 'PARTNER_ADMIN',
        permissions: ['partner:read', 'partner:write', 'integration:read', 'commission:read'],
        status: 'ACTIVE',
        isEmailVerified: true,
    },
    {
        _id: new Types.ObjectId('507f1f77bcf86cd799439059'),
        email: 'support@proactiv.com',
        password: 'Support@123456',
        firstName: 'Support',
        lastName: 'Staff',
        fullName: 'Support Staff',
        role: 'SUPPORT_STAFF',
        permissions: ['ticket:read', 'ticket:write', 'user:read', 'inquiry:read'],
        status: 'ACTIVE',
        isEmailVerified: true,
    },
];
